# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "ghafpkgs"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghaf"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2026 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  ".github/dependabot.yml",
  ".github/workflows/codeql.yml",
  ".github/workflows/dependency-review.yml",
  ".github/workflows/scorecards.yml",
  "flake.lock",
  "packages/art/ghaf-artwork/**/*.png",
  "packages/art/ghaf-artwork/**/*.jpg",
  "packages/art/ghaf-artwork/**/*.svg",
  "packages/art/ghaf-theme/**/*.svg",
  "packages/cpp/ghaf-audio-control/src/.gitignore",
  "packages/go/swtpm-proxy-shim/go.sum",
  "packages/python/ldap-query/ldap-query/README.md",
  "packages/python/ldap-query/ldap-query/uv.lock",
  "packages/python/vinotify/vinotify/README.md",
  "packages/python/vinotify/vinotify/uv.lock",
  "packages/python/ghaf-usb-applet/ghaf_usb_applet/README.md",
  "packages/python/ghaf-usb-applet/ghaf_usb_applet/uv.lock",
  "packages/python/gps-websock/gps-websock/uv.lock",
  "packages/python/gps-websock/gps-websock/README.md",
  "packages/rust/ghaf-kill-switch-app/Cargo.lock",
  "packages/rust/ghaf-mem-manager/Cargo.lock",
  "packages/rust/ghaf-nw-packet-forwarder/Cargo.lock",
  "packages/rust/ghaf-nw-packet-forwarder/flake.lock",
  "packages/update-deps/README.md",
  "SECURITY.md"
]

[[annotations]]
SPDX-License-Identifier = "LicenseRef-Unsplash"
SPDX-FileCopyrightText = "Unsplash"
precedence = "closest"
path = [
  "packages/art/ghaf-wallpapers/**/*.jpg"
]

[[annotations]]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "2022-2026 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  "docs/**/*.svg", "docs/**/*.png",
]

# External code

[[annotations]]
# See https://github.com/qemu/qemu/blob/master/LICENSE
# Our changes affect GPL-2.0-or-later parts only.
SPDX-License-Identifier = "GPL-2.0-or-later"
SPDX-FileCopyrightText = [
  "Fabrice Bellard and the QEMU team",
  "Copyright (c) 2021-2022 Canokeys.org <contact@canokeys.org>",
  "Written by Hongren (Zenithal) Zheng <i@zenithal.me>",
  "Copyright (c) 2019 Janus Technologies, Inc. (http://janustech.com)",
  "Copyright (C) 2008-2010 Kevin O'Connor <kevin@koconnor.net>",
  "Copyright (C) 2006 Fabrice Bellard",
  "Copyright (C) 2013 Red Hat Inc",
]
path = [
  "packages/qemu/ghaf-qemu/patches/*.patch",
  "packages/qemu/ghaf-qemu-bpmp/patches/*.patch",
  "packages/qemu/ghaf-qemu-bpmp/sources/**/*",
]
